events {
}

http {
    server {
        listen 443 ssl;
        server_name ckappe.42.fr;

        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        # upon file request look inside /var/www/html (that's where WordPress volume is mounted inside the WordPress container)
        root /var/www/html;
        index index.php index.html;

        location / {
            # For every URL, try to find a file matching the URL path. If that fails, try to find a directory. 
            # If that also fails, send the request to WordPress's index.php and keep the original query parameters.
            try_files $uri $uri/ /index.php?$args;
        }
        location ~ \.php$ {
            include fastcgi_params;
            # "Send PHP requests to port 9000 of the container named wordpress"
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
