# version: "3.9"

services:

  nginx:
    # Build this image yourself from this Dockerfile
    build: ./requirements/nginx
    # Give the resulting locally built image this name and tag
    image: nginx:1.0
    restart: always
    ports:
      # connects localhost:8080  ──►  port 80 (specified in nginx Dockerfile) // TO BE CHANGED to "443:443"
      - "443:443"
    # tells Compose to check first if wordpress container has been started
    depends_on:
      - wordpress
    volumes:
    - wordpress_data:/var/www/html
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:1.0
    restart: always

    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_HOST: mariadb

      DOMAIN_NAME: ${DOMAIN_NAME}

      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}

      WP_SECOND_USER: ${WP_SECOND_USER}
      WP_SECOND_PASSWORD: ${WP_SECOND_PASSWORD}
      WP_SECOND_EMAIL: ${WP_SECOND_EMAIL}

    depends_on:
      - mariadb

    volumes:
      - wordpress_data:/var/www/html

    networks:
      - inception


  mariadb:    
    build: ./requirements/mariadb
    image: mariadb:1.0
    restart: always
    
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}

    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ckappe/data/mariadb
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ckappe/data/wordpress


networks:
  inception: